App:
  SessionTimeout: 14400
  TimeZone: "Europe/Moscow"
  Domain: "localhost"
  Mode: "dev"
  DirWork: "/home/konstantin/work/sample/assets"

Workflow:
  Limitch: 1000      # буфер канала задач
  Limitpool: 9       # максимальное количество воркеров обслуживающих задачи

Http:
  Proto: "http"
  Host: "localhost"
  Port: 8080
  WriteTimeout: 60  # Время ожидания окончания передачи ответа в секундах, по истечении которого соединение сбрасывается
  ReadTimeout: 60   # Время ожидания web запроса в секундах, по истечении которого соединение сбрасывается
  MaxHeaderBytes: 1048576 # Максимальный размер заголовка получаемого от браузера клиента в байтах
  Proxy: "" # format: "http://login:pass@bproxy.msk.mts.ru:3131"
  Cors:
    AllowedOrigins: ["*"]
    AllowedMethods: ["HEAD", "GET", "POST", "PATСH", "PUT", "DELETE", "OPTIONS"]
    AllowedHeaders: ["Accept", "Authorization", "Content-Type", "X-CSRF-Token"]
    ExposedHeaders: ["Link"]
    AllowCredentials: true
    MaxAge: 300

Connect:
  Mysql:
    Host: "" # tcp(localhost:3306)
    Name: "accounter"
    Login: "root"
    Password: "root"
    Charset: "utf8"
    Migration: "/home/konstantin/work/sample/migration/mysql"
  Postgresql:
    Host: "localhost" # localhost
    Port: 5432
    Name: "test"
    Login: "postgres"
    Password: "postgres"
    Ssl: "disable"
    Charset: "utf8"
    Migration: "/home/konstantin/work/sample/migration/postgres"

Users:
  Name: "Vasya Pupkin"
  IsAccess: true
  Balance: 65.789
